# Generated by Django 4.2.5 on 2023-09-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="grupoCorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "afacturar",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "apagar",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "acortar",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                        ],
                        max_length=2,
                    ),
                ),
                ("hora", models.TimeField(default="23:59:59")),
            ],
            options={
                "verbose_name": "Grupo de corte",
                "verbose_name_plural": "Grupos de corte",
            },
        ),
        migrations.CreateModel(
            name="Mikrotik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ip", models.CharField(max_length=50)),
                ("puertoweb", models.IntegerField()),
                ("puertoapi", models.IntegerField()),
                ("puertowinbox", models.IntegerField()),
                ("interfazWan", models.CharField(blank=True, max_length=50, null=True)),
                ("interfazlan", models.CharField(blank=True, max_length=50, null=True)),
                ("usuario", models.CharField(max_length=60)),
                ("contraseña", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Mikrotik",
                "verbose_name_plural": "Servidores mikrotik",
            },
        ),
        migrations.CreateModel(
            name="planVelocidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField()),
                ("velocidad", models.CharField(max_length=9)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("R", "Residencial"), ("C", "Corporativo")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("burst_limit", models.CharField(default="0/0", max_length=7)),
                ("limit_at", models.CharField(default="0/0", max_length=7)),
                ("burst_threshold", models.CharField(default="0/0", max_length=13)),
                ("burst_time", models.CharField(default="0s/0s", max_length=5)),
                ("priority", models.CharField(default="8/8", max_length=3)),
            ],
            options={
                "verbose_name": "Plan de Velocidad",
                "verbose_name_plural": "Planes de Velocidad",
            },
        ),
        migrations.CreateModel(
            name="Segmentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segmento", models.CharField(max_length=18)),
                (
                    "mikro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mikrotik.mikrotik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmento",
                "verbose_name_plural": "Segmentos de red",
            },
        ),
    ]
