# Generated by Django 4.2.5 on 2023-09-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0004_alter_mikrotik_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupocorte",
            name="periodocobrar",
            field=models.CharField(
                choices=[("A", "Anticipado"), ("V", "Vencido")],
                default="A",
                max_length=1,
            ),
        ),
    ]
