# Generated by Django 4.2.5 on 2023-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0006_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                default="Activo",
                max_length=9,
            ),
        ),
    ]
