# Generated by Django 4.2.5 on 2023-10-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_zona_image"),
        ("mikrotik", "0007_servicio_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="zona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.zona",
            ),
        ),
    ]
