# Generated by Django 5.0.6 on 2024-07-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0009_servicio_tiposervicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planvelocidad",
            name="burst_limit",
        ),
        migrations.RemoveField(
            model_name="planvelocidad",
            name="burst_threshold",
        ),
        migrations.RemoveField(
            model_name="planvelocidad",
            name="burst_time",
        ),
        migrations.RemoveField(
            model_name="planvelocidad",
            name="limit_at",
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_limit_download",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_limit_upload",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_threshold_download",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_threshold_upload",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_time_download",
            field=models.CharField(default="0s", max_length=5),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="burst_time_upload",
            field=models.CharField(default="0s", max_length=5),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="limit_at_download",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="limit_at_upload",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="max_limit",
            field=models.CharField(default="10M/10M", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="parent",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="queue_type_download",
            field=models.CharField(default="default", max_length=7),
        ),
        migrations.AddField(
            model_name="planvelocidad",
            name="queue_type_upload",
            field=models.CharField(default="default", max_length=7),
        ),
    ]
