# Generated by Django 5.0.6 on 2024-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0010_remove_planvelocidad_burst_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="estadoservicio",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                default="Activo",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="tiposervicio",
            field=models.CharField(
                choices=[("IP estatica", "IP estatica"), ("PPPoE", "PPPoE")],
                default="IP estatica",
                max_length=12,
            ),
        ),
    ]
