# Generated by Django 5.0.6 on 2024-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0011_servicio_estadoservicio_alter_servicio_tiposervicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="mikrotik",
            name="segmento",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
