# Generated by Django 5.0.6 on 2024-07-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0012_mikrotik_segmento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mikrotik",
            old_name="segmento",
            new_name="segmentos_ip",
        ),
    ]
