# Generated by Django 5.0.6 on 2024-07-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0013_rename_segmento_mikrotik_segmentos_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="segmentoip",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
