# Generated by Django 5.0.6 on 2024-07-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0015_remove_servicio_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="passwordpppoe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="perfil",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="userpppoe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
