# Generated by Django 5.0.6 on 2024-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0016_servicio_passwordpppoe_servicio_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="tiposervicio",
            field=models.CharField(
                choices=[
                    ("----------", "----------"),
                    ("IP estatica", "IP estatica"),
                    ("PPPoE", "PPPoE"),
                ],
                default="----------",
                max_length=12,
            ),
        ),
    ]
