# Generated by Django 5.0.6 on 2024-09-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0017_alter_servicio_tiposervicio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicio",
            old_name="ip",
            new_name="ip_remote",
        ),
        migrations.AddField(
            model_name="servicio",
            name="ip_local",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="tiposervicio",
            field=models.CharField(
                choices=[
                    ("----------", "----------"),
                    ("estatica", "estatica"),
                    ("pppoe", "pppoe"),
                ],
                default="----------",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="PerfilPpp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "local_address",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "remote_address",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("dns1", models.CharField(blank=True, max_length=15, null=True)),
                ("dns2", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "change_tcp_mss",
                    models.CharField(
                        choices=[("no", "no"), ("yes", "yes"), ("default", "default")],
                        default="default",
                        max_length=7,
                    ),
                ),
                (
                    "use_upnp",
                    models.CharField(
                        choices=[("no", "no"), ("yes", "yes"), ("default", "default")],
                        default="default",
                        max_length=7,
                    ),
                ),
                (
                    "use_mpls",
                    models.CharField(
                        choices=[
                            ("no", "no"),
                            ("yes", "yes"),
                            ("required", "required"),
                            ("default", "default"),
                        ],
                        default="default",
                        max_length=9,
                    ),
                ),
                (
                    "use_compression",
                    models.CharField(
                        choices=[
                            ("no", "no"),
                            ("yes", "yes"),
                            ("required", "required"),
                            ("default", "default"),
                        ],
                        default="default",
                        max_length=9,
                    ),
                ),
                (
                    "use_encryption",
                    models.CharField(
                        choices=[
                            ("no", "no"),
                            ("yes", "yes"),
                            ("required", "required"),
                            ("default", "default"),
                        ],
                        default="default",
                        max_length=9,
                    ),
                ),
                ("rate_limit", models.CharField(default="10M/10M", max_length=9)),
                (
                    "only_one",
                    models.CharField(
                        choices=[("no", "no"), ("yes", "yes"), ("default", "default")],
                        default="default",
                        max_length=7,
                    ),
                ),
                (
                    "mikrotik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mikrotik.mikrotik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil PPPoE",
                "verbose_name_plural": "Perfiles PPPoE",
            },
        ),
    ]
