# Generated by Django 5.0.6 on 2024-10-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_zona_image"),
        ("mikrotik", "0018_rename_ip_servicio_ip_remote_servicio_ip_local_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("coordenadas", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "publicas_recibidas",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "recepcion",
                    models.CharField(
                        choices=[("FO", "Fibra optica"), ("I", "Inhalambrico")],
                        default="FO",
                        max_length=20,
                    ),
                ),
                (
                    "equipo_proveedor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "imagen_equipo_proveedor",
                    models.ImageField(blank=True, null=True, upload_to="Nodo/%Y/%m/%d"),
                ),
                (
                    "equipo_propio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "imagen_equpo_propio",
                    models.ImageField(blank=True, null=True, upload_to="Nodo/%Y/%m/%d"),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "mikrotik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mikrotik.mikrotik",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clientes.zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nodo",
                "verbose_name_plural": "Nodos",
            },
        ),
        migrations.CreateModel(
            name="Torre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("estacion_ip", models.CharField(max_length=15)),
                ("coordenadas", models.CharField(blank=True, max_length=50, null=True)),
                ("ap", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "nodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mikrotik.nodo"
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clientes.zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acess Point",
                "verbose_name_plural": "Acess Points",
            },
        ),
        migrations.CreateModel(
            name="Accesspoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ip", models.CharField(max_length=15)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accesspoint/%Y/%m/%d"
                    ),
                ),
                ("ssid", models.CharField(max_length=50)),
                ("seguridad", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "nodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mikrotik.nodo",
                    ),
                ),
                (
                    "torre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mikrotik.torre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acess Point",
                "verbose_name_plural": "Acess Points",
            },
        ),
    ]
