# Generated by Django 5.0.6 on 2024-10-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0019_nodo_torre_accesspoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="torre",
            options={"verbose_name": "Torres", "verbose_name_plural": "Torres"},
        ),
    ]
