# Generated by Django 5.0.6 on 2024-10-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0020_alter_torre_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="torre",
            name="ap",
        ),
    ]
