# Generated by Django 4.2.5 on 2023-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="documento",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
