# Generated by Django 4.2.5 on 2023-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_documento_alter_cliente_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
            },
        ),
    ]
