# Generated by Django 4.2.5 on 2023-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_zona"),
    ]

    operations = [
        migrations.AddField(
            model_name="zona",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="clientes/%Y/%n/%d"
            ),
        ),
    ]
