# Generated by Django 4.2.5 on 2023-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_zona_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zona",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="clientes/%Y/%m/%d"
            ),
        ),
    ]
