# Generated by Django 5.0.6 on 2024-09-25 20:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0005_alter_zona_image"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(default=datetime.datetime.now)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                ("cantidad", models.IntegerField(default=0)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.sale",
                    ),
                ),
            ],
        ),
    ]
